image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - builder
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
build:
  stage: build
  script:
    - docker buildx create --name multiarch --driver docker-container --use || true
    - docker buildx inspect --bootstrap
    - docker buildx build --pull -f Dockerfile --platform linux/amd64,linux/arm64 --push -t $CONTAINER_RELEASE_IMAGE .